Remove PCB from BOM generation
AllSpiceIO/py-allspice pull request #83
Opened 2024-04-23 16:42 UTC by shrik450

Closes #55.

This change removes the `pcbdoc_file` path from the `generate_bom_for_altium` util, and updates the logic to build and traverse the hierarchy of schdoc files instead. This is a breaking change, as the public api of the library has changed. This change also introduces the usage of `configparser` to read the PrjPcb file instead of using a regex, as this will be useful for future changes to the BOM generation. This is the first of three PRs that will change the BOM generation function. 

The test file has to be updated because the new method produces the CSV in a different order.

2024-04-24 19:22 UTC, kdumontnu commented
@shrik450 did you try running this on any other test files? Searching for .PrjPcb on GitHub should provide some results.

2024-04-29 16:13 UTC, kdumontnu requested changes
Currently, this will fail with schematics that are nested in a directory relative to the project file. I believe it's because the sheet reference in schematic we're using to build the hierarchy is relative to the schematic file (usually in the same directory, though not necessarily), but the file locations in the project file are relative to the project file.

So, I believe we just need to prepend the relative path from project file to the schematic file in the graph.

I added you to a demo here: https://test.allspice.dev/app_path/test/TestHierarchy

Also, see https://github.com/AllSpiceIO/py-allspice/pull/85

2024-04-29 16:26 UTC, kdumontnu commented
Also, this is a bit out of scope of this PR, but the logic behind grouping and attributes is a bit flawed, at least with how we output the json data from tools.

Altium hard-codes a few attribute names, including one we use as `part_id` (see below) and one for "description". But we don't include it in attributes in the json, so the user can't access them using the attributes_map json. However, these are almost certainly what the user will want to group by (if they want to group components).

![image](https://github.com/AllSpiceIO/py-allspice/assets/12700993/bc2cc96e-865f-427f-afbf-0c03f47a995c)

2024-04-30 14:00 UTC, shrik450 commented
> Also, this is a bit out of scope of this PR, but the logic behind grouping and attributes is a bit flawed, at least with how we output the json data from tools.

This is resolved in #84, including the part_id and description.

2024-04-30 15:22 UTC, shrik450 commented
> Currently, this will fail with schematics that are nested in a directory relative to the project file. I believe it's because the sheet reference in schematic we're using to build the hierarchy is relative to the schematic file (usually in the same directory, though not necessarily), but the file locations in the project file are relative to the project file.
> 
> So, I believe we just need to prepend the relative path from project file to the schematic file in the graph.
> 
> I added you to a demo here: https://test.allspice.dev/app_path/test/TestHierarchy

Thanks for the example - I tried this out myself and see the issue. I think resolving all paths to be relative to the project at all times is probably the best solution for this.

Do you mind if I clone that repo to AllSpice Mirrors and use it as a test case? It's a good case in general for relative paths.

2024-04-30 20:18 UTC, McRaeAlex approved these changes

2024-04-30 20:49 UTC, shrik450 commented
@kdumontnu I've fixed the issue with the relative paths. Can you confirm if I can use that repo as a test case? If so, I will update this PR to include the test.

2024-04-30 20:53 UTC, kdumontnu commented
> @kdumontnu I've fixed the issue with the relative paths. Can you confirm if I can use that repo as a test case? If so, I will update this PR to include the test.

Oh, yeah feel free to use that file in a test.

2024-05-01 11:33 UTC, kdumontnu approved these changes
👍

2024-05-01 14:09 UTC, merged